### ISSUE TITLE
can't find documentation how to use this?

### ISSUE THREAD

**Issue by despiegk** [openvstorage/tgt#2]

**Comment by wimpers** [comment]
https://openvstorage.gitbooks.io/openvstorage/content/Administration/createvdisk.html#iscsi

Will make sure there is documentation around this also here

**Comment by despiegk** [comment]
need to make sure that every repo has enough docs to be used independently, also ok to link to content of other repo's where required, ps we have a tool to get content from other repo's and put in1 doc so there is no duplication

**Comment by wimpers** [comment]
@despiegk any information/documentation about that tool?

**Comment by wimpers** [comment]
https://www.gitbook.com/book/openvstorage/tgt/details
