### ISSUE TITLE
use tgt create lun error

### ISSUE THREAD

**Issue by run283092610** [openvstorage/tgt#7]
Hi,
I use tihs way https://www.gitbook.com/book/openvstorage/tgt create three tgt packages to install 
the package 
tgt-dbg_1.0.63-0ovs1.4-1ubuntu1.1_amd64.deb
tgt-openvstorage_1.0.63-0ovs1.4-1ubuntu1.1_amd64.deb
tgt_1.0.63-0ovs1.4-1ubuntu1.1_amd64.deb

then is execute tgtadm --lld iscsi --mode target --op new --tid=1 --targetname iqn.2016-01.com.openvstorage:for.all
 
when i execute the command  
tgtadm --lld iscsi --op new --bstype openvstorage --mode logicalunit --tid 1 --lun 1 -b lcoalhost/mnt/pool-1/disk-1.raw 
tgtadm: invalid request

the log is
Nov 30 15:26:01 ovs006 tgtd[15990]: tgtd: device_mgmt(246) sz:57 params:path=lcoalhost/mnt/pool-1/disk-1.raw,bstype=openvstorage
Nov 30 15:26:01 ovs006 tgtd[15990]: tgtd: bs_thread_open(409) 16
Nov 30 15:26:01 ovs006 tgtd[15990]: tgtd: bs_openvstorage_open_helper(414) bs_openvstorage_open_helper: cannot open volume: Input/output error

when i execute the command
tgtadm --lld iscsi --op new --bstype openvstorage+tcp --mode logicalunit --tid 1 --lun 1 -b lcoalhost/mnt/pool-1/disk-1.raw 
tgtadm: invalid request

the log is
Nov 30 15:29:20 ovs006 tgtd[15990]: tgtd: device_mgmt(246) sz:61 params:path=lcoalhost/mnt/pool-1/disk-1.raw,bstype=openvstorage+tcp
Nov 30 15:29:20 ovs006 tgtd[15990]: tgtd: bs_thread_open(409) 16
Nov 30 15:29:20 ovs006 tgtd[15990]: tgtd: bs_openvstorage_open_helper(386) bs_openvstorage_open_helper: cannot set transport type: Input/output error

how can i solve this problems
Thanks

**Comment by run283092610** [comment]
strace tgtadm --lld iscsi --op new --bstype openvstorage --mode logicalunit --tid 1 --lun 1 -b /mnt/pool-1/disk-1.raw 
execve("/usr/sbin/tgtadm", ["tgtadm", "--lld", "iscsi", "--op", "new", "--bstype", "openvstorage", "--mode", "logicalunit", "--tid", "1", "--lun", "1", "-b", "/mnt/pool-1/disk-1.raw"], [/* 23 vars */]) = 0
brk(NULL)                               = 0xe5b000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe8694c1000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=56786, ...}) = 0
mmap(NULL, 56786, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fe8694b3000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1868984, ...}) = 0
mmap(NULL, 3971488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fe868ed4000
mprotect(0x7fe869094000, 2097152, PROT_NONE) = 0
mmap(0x7fe869294000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1c0000) = 0x7fe869294000
mmap(0x7fe86929a000, 14752, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fe86929a000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe8694b2000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe8694b1000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe8694b0000
arch_prctl(ARCH_SET_FS, 0x7fe8694b1700) = 0
mprotect(0x7fe869294000, 16384, PROT_READ) = 0
mprotect(0x605000, 4096, PROT_READ)     = 0
mprotect(0x7fe8694c3000, 4096, PROT_READ) = 0
munmap(0x7fe8694b3000, 56786)           = 0
brk(NULL)                               = 0xe5b000
brk(0xe7c000)                           = 0xe7c000
socket(PF_LOCAL, SOCK_STREAM, 0)        = 3
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/tgtd/socket.0"}, 110) = 0
write(3, "\2\0\0\0\0\0\0\0iscsi\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 120) = 120
write(3, "path=/mnt/pool-1/disk-1.raw,bsty"..., 48) = 48
recvfrom(3, "\21\0\0\0\10\0\0\0", 8, MSG_WAITALL, NULL, NULL) = 8
write(2, "tgtadm: invalid request\n", 24tgtadm: invalid request
) = 24
close(3)                                = 0
exit_group(22)                          = ?
+++ exited with 22 +++

**Comment by wimpers** [comment]
`lcoalhost/mnt/pool-1/disk-1.raw`

This is probably a typo. it should be `localhost`. Do not that I haven't tried it with localhost. I  use the IP of the Storage Router on which the the vPool is exposed f.e.10.100.188.31:26203/volumeName where 10.100.188.31 is SR on which the vPool is exposed, 26203 the port for the edge for that vpool and volumeName the name of the volume (should already be created in that vPool)

**Comment by wimpers** [comment]
Re-open if needed.

**Comment by fredohouse** [comment]
Hello I have the same pb: 
tgtadm --lld iscsi --op new --bstype openvstorage+tcp --mode logicalunit --tid 1 --lun 1 -b 10.160.52.101:26203/testiscsi
tgtadm: invalid request
