### ISSUE TITLE
Make tgt rpm package for centos

### ISSUE THREAD

**Issue by run283092610** [openvstorage/tgt#8]
hi
  i use this way https://www.gitbook.com/book/openvstorage/tgt/details 
to build tgt rpm package .when i command ./tgt/jenkins/centos/build_rpms.sh 
is error

the error information

>>> BUILD RPMS <<<
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.cK0Rde
+ umask 022
+ cd /home/jenkins/workspace/tgt/rpm/BUILD
+ cd /home/jenkins/workspace/tgt/rpm/BUILD
+ rm -rf tgt-1.0.43
+ /usr/bin/tar -xf -
+ /usr/bin/gzip -dc /home/jenkins/workspace/tgt/rpm/SOURCES/v1.0.43.tar.gz
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd tgt-1.0.43
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ echo 'Patch #0 (0001-redhatify-docs.patch):'
Patch #0 (0001-redhatify-docs.patch):
+ /usr/bin/patch -p1 --fuzz=0
+ /usr/bin/cat /home/jenkins/workspace/tgt/rpm/SOURCES/0001-redhatify-docs.patch
patching file README
patching file doc/README.iscsi
patching file doc/README.iser
+ echo 'Patch #1 (0002-remove-check-for-xsltproc.patch):'
Patch #1 (0002-remove-check-for-xsltproc.patch):
+ /usr/bin/patch -p1 --fuzz=0
+ /usr/bin/cat /home/jenkins/workspace/tgt/rpm/SOURCES/0002-remove-check-for-xsltproc.patch
patching file doc/Makefile
+ echo 'Patch #2 (0003-default-config.patch):'
Patch #2 (0003-default-config.patch):
+ /usr/bin/patch -p1 --fuzz=0
+ /usr/bin/cat /home/jenkins/workspace/tgt/rpm/SOURCES/0003-default-config.patch
patching file scripts/initd.sample
patching file scripts/tgt-admin
+ echo 'Patch #9999 (openvstorage_tgt.patch):'
Patch #9999 (openvstorage_tgt.patch):
+ /usr/bin/patch -p1 --fuzz=0
+ /usr/bin/cat /home/jenkins/workspace/tgt/rpm/SOURCES/openvstorage_tgt.patch
patching file debian/bash-completion
patching file debian/changelog
patching file debian/compat
patching file debian/control
patching file debian/copyright
patching file debian/gbp.conf
patching file debian/init
patching file debian/patches/add-iser-discovery-support.patch
patching file debian/patches/conf-makefile
patching file debian/patches/fix-config-regression.patch
patching file debian/patches/fix-read-response-buffer.patch
patching file debian/patches/fix_delayed_management_request.patch
patching file debian/patches/fix_leak_of_task_in_scsi_flag.patch
patching file debian/patches/series
patching file debian/rules
patching file debian/source/format
patching file debian/tests/admin
patching file debian/tests/control
patching file debian/tests/daemon
patching file debian/upstart
patching file debian/watch
patching file usr/Makefile
patching file usr/bs_openvstorage.c
patching file jenkins/ubuntu/build_debs.sh
patching file jenkins/ubuntu/docker/Dockerfile
patching file jenkins/ubuntu/docker/docker-entrypoint.sh
patching file jenkins/ubuntu/docker/supervisord.conf
patching file jenkins/centos/build_rpms.sh
patching file jenkins/centos/docker/Dockerfile
patching file jenkins/centos/docker/docker-entrypoint.sh
patching file jenkins/centos/docker/supervisord.conf
patching file rpm/SOURCES/0001-redhatify-docs.patch
patching file rpm/SOURCES/0002-remove-check-for-xsltproc.patch
patching file rpm/SOURCES/0003-default-config.patch
patching file rpm/SOURCES/sample.conf
patching file rpm/SOURCES/sysconfig.tgtd
patching file rpm/SOURCES/targets.conf
patching file rpm/SOURCES/tgtd.conf
patching file rpm/SOURCES/tgtd.service
patching file rpm/SPECS/scsi-target-utils.spec
patching file README.openvstorage
patching file jenkins/ubuntu/build_debs.sh
patching file jenkins/ubuntu/build_debs.sh
patching file scripts/tgt-admin
patching file usr/bs_openvstorage.c
patching file jenkins/ubuntu/build_debs.sh
patching file jenkins/ubuntu/build_debs.sh
patching file jenkins/ubuntu/build_debs.sh
patching file README.openvstorage
patching file debian/control
patching file jenkins/centos/build_rpms.sh
patching file jenkins/ubuntu/build_debs.sh
patching file debian/changelog
patching file GITBOOK.md
patching file SUMMARY.md
patching file book.json
patching file README.openvstorage
patching file README
patching file README
patching file README
patching file debian/changelog
patching file debian/control
patching file usr/bs_openvstorage.c
patching file jenkins/ubuntu1604/build_debs.sh
patching file jenkins/ubuntu1604/docker/Dockerfile
patching file jenkins/ubuntu1604/docker/docker-entrypoint.sh
patching file jenkins/ubuntu1604/docker/supervisord.conf
patching file debian/control
patching file debian/changelog
patching file debian/changelog
patching file debian/control
patching file debian/changelog
patching file usr/bs_openvstorage.c
patching file Makefile
patching file conf/Makefile
patching file debian/changelog
patching file debian/compat
patching file debian/control
patching file debian/copyright
patching file debian/gbp.conf
patching file debian/patches/add-iser-discovery-support.patch
patching file debian/patches/conf-makefile
patching file debian/patches/fix-config-regression.patch
patching file debian/patches/fix-read-response-buffer.patch
patching file debian/patches/fix_delayed_management_request.patch
patching file debian/patches/fix_leak_of_task_in_scsi_flag.patch
patching file debian/patches/series
patching file debian/rules
patching file debian/tests/admin
patching file debian/tests/control
patching file debian/tests/daemon
patching file debian/tests/storage
patching file debian/tgt-openvstorage.install
patching file debian/tgt-rbd.install
patching file debian/tgt.NEWS
patching file debian/tgt.bash-completion (renamed from debian/bash-completion)
patching file debian/tgt.docs
patching file debian/tgt.init (renamed from debian/init)
patching file debian/tgt.postinst
patching file debian/tgt.prerm
patching file debian/tgt.service
patching file debian/upstart
patching file debian/watch
patching file doc/Makefile
Hunk #3 FAILED at 32.
1 out of 3 hunks FAILED -- saving rejects to file doc/Makefile.rej
patching file doc/README.dvdjukebox
patching file doc/README.glfs
patching file doc/README.iscsi
Hunk #1 succeeded at 28 (offset 3 lines).
Hunk #2 succeeded at 116 (offset 3 lines).
Hunk #3 succeeded at 227 (offset 3 lines).
patching file doc/README.rbd
patching file doc/README.sheepdog
patching file doc/targets.conf.5.xml
patching file doc/tgtadm.8.xml
patching file doc/tgtd.8.xml
patching file scripts/deb/control
patching file scripts/deb/patches/0001-Use-local-docbook-for-generating-docs.patch
patching file scripts/tgt-admin
patching file scripts/tgtd.service
patching file scripts/tgtd.spec
patching file usr/Makefile
patching file usr/bs.c
patching file usr/bs_aio.c
patching file usr/bs_glfs.c
patching file usr/bs_rbd.c
patching file usr/bs_rdwr.c
patching file usr/bs_sheepdog.c
patching file usr/bs_ssc.c
patching file usr/bs_thread.h
patching file usr/iscsi/conn.c
patching file usr/iscsi/iscsi_tcp.c
patching file usr/iscsi/iscsid.c
patching file usr/iscsi/iser.c
patching file usr/iscsi/iser.h
patching file usr/iscsi/iser_text.c
patching file usr/iscsi/session.c
patching file usr/iscsi/target.c
patching file usr/libssc.c
patching file usr/mgmt.c
patching file usr/mmc.c
patching file usr/sbc.c
patching file usr/scsi.c
patching file usr/scsi.h
patching file usr/smc.c
patching file usr/smc.h
patching file usr/spc.c
patching file usr/target.c
patching file usr/tgtadm.c
patching file usr/tgtadm.h
patching file usr/tgtd.c
patching file usr/tgtd.h
patching file usr/util.h
error: Bad exit status from /var/tmp/rpm-tmp.cK0Rde (%prep)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.cK0Rde (%prep)

and the /var/tmp/rpm-tmp.cK0Rde 
#!/bin/sh

  RPM_SOURCE_DIR="/home/jenkins/workspace/tgt/rpm/SOURCES"
  RPM_BUILD_DIR="/home/jenkins/workspace/tgt/rpm/BUILD"
  RPM_OPT_FLAGS="-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic"
  RPM_LD_FLAGS="-Wl,-z,relro "
  RPM_ARCH="x86_64"
  RPM_OS="linux"
  export RPM_SOURCE_DIR RPM_BUILD_DIR RPM_OPT_FLAGS RPM_LD_FLAGS RPM_ARCH RPM_OS
  RPM_DOC_DIR="/usr/share/doc"
  export RPM_DOC_DIR
  RPM_PACKAGE_NAME="scsi-target-utils-openvstorage"
  RPM_PACKAGE_VERSION="1.0.43"
  RPM_PACKAGE_RELEASE="4.el7.centos"
  export RPM_PACKAGE_NAME RPM_PACKAGE_VERSION RPM_PACKAGE_RELEASE
  LANG=C
  export LANG
  unset CDPATH DISPLAY ||:
  RPM_BUILD_ROOT="/home/jenkins/workspace/tgt/rpm/BUILDROOT/scsi-target-utils-openvstorage-1.0.43-4.el7.centos.x86_64"
  export RPM_BUILD_ROOT
  
  PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/lib64/pkgconfig:/usr/share/pkgconfig"
  export PKG_CONFIG_PATH
  
  set -x
  umask 022
  cd "/home/jenkins/workspace/tgt/rpm/BUILD"
cd '/home/jenkins/workspace/tgt/rpm/BUILD'
rm -rf 'tgt-1.0.43'
/usr/bin/gzip -dc '/home/jenkins/workspace/tgt/rpm/SOURCES/v1.0.43.tar.gz' | /usr/bin/tar -xf - 
STATUS=$?
if [ $STATUS -ne 0 ]; then
  exit $STATUS
fi
cd 'tgt-1.0.43'
/usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
echo "Patch #0 (0001-redhatify-docs.patch):"
/usr/bin/cat /home/jenkins/workspace/tgt/rpm/SOURCES/0001-redhatify-docs.patch | /usr/bin/patch  -p1  --fuzz=0

echo "Patch #1 (0002-remove-check-for-xsltproc.patch):"
/usr/bin/cat /home/jenkins/workspace/tgt/rpm/SOURCES/0002-remove-check-for-xsltproc.patch | /usr/bin/patch  -p1  --fuzz=0

echo "Patch #2 (0003-default-config.patch):"
/usr/bin/cat /home/jenkins/workspace/tgt/rpm/SOURCES/0003-default-config.patch | /usr/bin/patch  -p1  --fuzz=0

echo "Patch #9999 (openvstorage_tgt.patch):"
/usr/bin/cat /home/jenkins/workspace/tgt/rpm/SOURCES/openvstorage_tgt.patch | /usr/bin/patch  -p1  --fuzz=0

## git apply -v --whitespace=nowarn --exclude=rpm/* --exclude=debian/* --exclude=jenkins/* /home/jenkins/workspace/tgt/rpm/SOURCES/openvstorage_tgt.patch

exit 0

it looks like the patch have problem .how can i solve it
thanks

**Comment by run283092610** [comment]
the openvstorage_tgt.patch does it contain some special features for openvstorage. Do I have to add it
thanks

**Comment by wimpers** [comment]
Hi,

the latest OVS version no longer works on CentOS (and hence rmp) and there is currently no plan to get the OVS functionality working again. Best approach is to use Ubuntu 16.04 to run OVS.
